package org.oos.travel;

import org.skife.jdbi.v2.sqlobject.*;
import org.skife.jdbi.v2.sqlobject.customizers.RegisterMapper;

import java.sql.ResultSet;
import java.util.List;

@RegisterMapper(VisaMapper.class)
public interface VisaDAO {
    @SqlUpdate("create table if not exists visa (id int GENERATED BY DEFAULT AS IDENTITY, name varchar(100), address varchar(255))")
    void createVisaTable();

    @SqlUpdate("insert into visa (name, address) values (:name, :address)")
    void insert(@Bind("name") String name, @Bind("address") String address);

    @SqlQuery("CALL IDENTITY()")
    long insertedId();

    @SqlQuery("select name from visa where id = :id")
    String findNameById(@Bind("id") int id);

    @SqlQuery("select * from visa where id = :id")
    Visa findById(@Bind("id") long id);

    @SqlQuery("select * from visa")
    List<Visa> findAll();
}
